set define off
whenever sqlerror exit failure rollback

begin execute immediate 'drop table AI_NL2SQL_LOG purge';
exception when others then if sqlcode != -942 then raise; end if; end;
/
create table AI_NL2SQL_LOG (
  log_id        number generated by default as identity primary key,
  request_id    varchar2(32) not null,
  created_at    timestamp default systimestamp not null,
  app_user      varchar2(255),
  question      varchar2(4000),
  view_used     varchar2(128),
  sql_text      clob,
  guard_status  varchar2(30),
  exec_status   varchar2(30),
  row_count     number,
  llm_ms        number,
  exec_ms       number,
  err_code      number,
  err_msg       varchar2(4000)
);

create index AI_NL2SQL_LOG_I1 on AI_NL2SQL_LOG(created_at);
create index AI_NL2SQL_LOG_I2 on AI_NL2SQL_LOG(request_id);

comment on table AI_NL2SQL_LOG is 'NL->SQL: log techniczny requestow (pytanie, sql, guard, czasy).';
comment on column AI_NL2SQL_LOG.log_id is 'PK; techniczny identyfikator logu.';
comment on column AI_NL2SQL_LOG.request_id is 'Id korelacji; przyklad: 32 znaki hex.';
comment on column AI_NL2SQL_LOG.created_at is 'Czas zapisu; timestamp.';
comment on column AI_NL2SQL_LOG.app_user is 'Uzytkownik APEX/DB; identyfikacja aktora.';
comment on column AI_NL2SQL_LOG.question is 'Tekst pytania NL.';
comment on column AI_NL2SQL_LOG.view_used is 'Widok whitelista; np. AI_V_SALES_ORDER_LINES.';
comment on column AI_NL2SQL_LOG.sql_text is 'SQL wygenerowany; tylko SELECT.';
comment on column AI_NL2SQL_LOG.guard_status is 'Wynik guarda; OK/BLOCKED/ERROR.';
comment on column AI_NL2SQL_LOG.exec_status is 'Status wykonania; OK/ERROR.';
comment on column AI_NL2SQL_LOG.row_count is 'Liczba wierszy (opcjonalnie).';
comment on column AI_NL2SQL_LOG.llm_ms is 'Czas LLM call w ms (v0 = 0).';
comment on column AI_NL2SQL_LOG.exec_ms is 'Czas wykonania SQL w ms.';
comment on column AI_NL2SQL_LOG.err_code is 'Kod bledu Oracle.';
comment on column AI_NL2SQL_LOG.err_msg is 'Opis bledu (skrocony).';

begin execute immediate 'drop table AI_NL2SQL_WHITELIST purge';
exception when others then if sqlcode != -942 then raise; end if; end;
/
create table AI_NL2SQL_WHITELIST (
  view_name   varchar2(128) primary key,
  enabled_yn  char(1) default 'Y' not null,
  purpose     varchar2(1000),
  created_at  timestamp default systimestamp not null
);

comment on table AI_NL2SQL_WHITELIST is 'NL->SQL: whitelista widokow dozwolonych w generowanym SQL.';
comment on column AI_NL2SQL_WHITELIST.view_name is 'PK; nazwa widoku dozwolonego.';
comment on column AI_NL2SQL_WHITELIST.enabled_yn is 'Czy wlaczone; Y/N.';
comment on column AI_NL2SQL_WHITELIST.purpose is 'Opis zastosowania widoku.';
comment on column AI_NL2SQL_WHITELIST.created_at is 'Czas dodania wpisu.';

merge into AI_NL2SQL_WHITELIST t
using (
  select 'AI_V_SALES_ORDER_LINES' view_name, 'Y' enabled_yn,
         'Pozycje zamowien z klientem i produktem.' purpose from dual
  union all
  select 'AI_V_SALES_ORDER_DAILY', 'Y',
         'Agregacja dzienna per status i waluta.' from dual
) s
on (t.view_name = s.view_name)
when matched then update set t.enabled_yn = s.enabled_yn, t.purpose = s.purpose
when not matched then insert (view_name, enabled_yn, purpose) values (s.view_name, s.enabled_yn, s.purpose);

commit;
