-- db/install.sql
-- Instalator v1 (dev/test). W prod: migracje, nie "drop & recreate".

set define off
set serveroutput on
set feedback on
set pagesize 200
set linesize 200
whenever sqlerror exit failure rollback

prompt === install.sql start ===
prompt User:
select user from dual;

prompt === 0) Best-effort: role + grants (may fail on APEX Cloud) ===
declare
  e_ins_priv exception;
  pragma exception_init(e_ins_priv, -1031); -- ORA-01031
begin
  begin
    execute immediate 'create role AI_QUERY_ROLE';
    dbms_output.put_line('OK: created role AI_QUERY_ROLE');
  exception
    when e_ins_priv then
      dbms_output.put_line('SKIP: no privilege to create role AI_QUERY_ROLE');
    when others then
      if sqlcode = -1921 then
        dbms_output.put_line('OK: role AI_QUERY_ROLE already exists');
      else
        raise;
      end if;
  end;
end;
/
-- grants will be attempted after views exist

prompt === 1) Infra tables for NL->SQL (log + whitelist) ===

begin
  execute immediate 'drop table AI_NL2SQL_LOG purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/
create table AI_NL2SQL_LOG (
  log_id        number generated by default as identity primary key,
  request_id    varchar2(32),
  created_at    timestamp default systimestamp not null,
  app_user      varchar2(255),
  question      varchar2(4000),
  view_used     varchar2(128),
  sql_text      clob,
  binds_json    clob,
  guard_status  varchar2(30),
  guard_reason  varchar2(1000),
  exec_status   varchar2(30),
  row_count     number,
  llm_ms        number,
  exec_ms       number,
  err_code      number,
  err_msg       varchar2(4000)
);

create index AI_NL2SQL_LOG_I1 on AI_NL2SQL_LOG(created_at);
create index AI_NL2SQL_LOG_I2 on AI_NL2SQL_LOG(request_id);

comment on table AI_NL2SQL_LOG is 'NL->SQL: log techniczny requestow (pytanie, sql, guard, czasy). Do debug i metryk.';
comment on column AI_NL2SQL_LOG.log_id is 'PK; techniczny identyfikator logu.';
comment on column AI_NL2SQL_LOG.request_id is 'Id korelacji; przyklad: 32 znaki hex.';
comment on column AI_NL2SQL_LOG.created_at is 'Czas zapisu; timestamp.';
comment on column AI_NL2SQL_LOG.app_user is 'Uzytkownik APEX/DB; identyfikacja aktora.';
comment on column AI_NL2SQL_LOG.question is 'Tekst pytania NL; bez sekretow.';
comment on column AI_NL2SQL_LOG.view_used is 'Widok z whitelisty uzyty do zapytania; np. AI_V_SALES_ORDER_LINES.';
comment on column AI_NL2SQL_LOG.sql_text is 'SQL wygenerowany przez NL->SQL; tylko SELECT.';
comment on column AI_NL2SQL_LOG.binds_json is 'Bindy w formacie JSON; bez wrazliwych wartosci.';
comment on column AI_NL2SQL_LOG.guard_status is 'Wynik guarda; np. OK/BLOCKED/ERROR.';
comment on column AI_NL2SQL_LOG.guard_reason is 'Powod blokady lub blad walidacji.';
comment on column AI_NL2SQL_LOG.exec_status is 'Status wykonania; OK/ERROR.';
comment on column AI_NL2SQL_LOG.row_count is 'Liczba zwroconych wierszy (po limicie).';
comment on column AI_NL2SQL_LOG.llm_ms is 'Czas LLM call w ms.';
comment on column AI_NL2SQL_LOG.exec_ms is 'Czas wykonania SQL w ms.';
comment on column AI_NL2SQL_LOG.err_code is 'Kod bledu Oracle (jesli exec error).';
comment on column AI_NL2SQL_LOG.err_msg is 'Opis bledu (skrocony).';

begin
  execute immediate 'drop table AI_NL2SQL_WHITELIST purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/
create table AI_NL2SQL_WHITELIST (
  view_name   varchar2(128) primary key,
  enabled_yn  char(1) default 'Y' not null,
  purpose     varchar2(1000),
  created_at  timestamp default systimestamp not null
);

comment on table AI_NL2SQL_WHITELIST is 'NL->SQL: whitelista obiektow dozwolonych w generowanym SQL.';
comment on column AI_NL2SQL_WHITELIST.view_name is 'PK; nazwa widoku dozwolonego; np. AI_V_SALES_ORDER_LINES.';
comment on column AI_NL2SQL_WHITELIST.enabled_yn is 'Czy wlaczone; Y/N.';
comment on column AI_NL2SQL_WHITELIST.purpose is 'Opis zastosowania widoku; dla kontekstu i kontroli.';
comment on column AI_NL2SQL_WHITELIST.created_at is 'Czas dodania wpisu.';

prompt === 2) Domain + views + comments + seed ===
@@seed/sales_seed.sql

prompt === 3) Seed whitelist entries (based on SALES seed views) ===
merge into AI_NL2SQL_WHITELIST t
using (
  select 'AI_V_SALES_ORDER_LINES' view_name, 'Y' enabled_yn,
         'Pozycje zamowien z klientem i produktem (najczesciej do analiz i filtrow).' purpose
  from dual
  union all
  select 'AI_V_SALES_ORDER_DAILY', 'Y',
         'Agregacja dzienna per status i waluta (szybkie wykresy i trendy).' purpose
  from dual
) s
on (t.view_name = s.view_name)
when matched then
  update set t.enabled_yn = s.enabled_yn, t.purpose = s.purpose
when not matched then
  insert (view_name, enabled_yn, purpose)
  values (s.view_name, s.enabled_yn, s.purpose);

commit;

prompt === 4) Best-effort: grants to AI_QUERY_ROLE (may fail) ===
declare
  e_ins_priv exception;
  pragma exception_init(e_ins_priv, -1031); -- ORA-01031
begin
  begin
    execute immediate 'grant select on AI_V_SALES_ORDER_LINES to AI_QUERY_ROLE';
    execute immediate 'grant select on AI_V_SALES_ORDER_DAILY to AI_QUERY_ROLE';
    dbms_output.put_line('OK: granted select on AI_V_SALES_* to AI_QUERY_ROLE');
  exception
    when e_ins_priv then
      dbms_output.put_line('SKIP: no privilege to grant to AI_QUERY_ROLE');
    when others then
      if sqlcode in (-1919, -1921) then
        dbms_output.put_line('SKIP: role missing or conflict (AI_QUERY_ROLE)');
      else
        raise;
      end if;
  end;
end;
/

prompt === 5) Packages (NL->SQL v0 stub) ===
@@plsql/ai_log.pks
@@plsql/ai_log.pkb
@@plsql/ai_sql_guard.pks
@@plsql/ai_sql_guard.pkb
@@plsql/ai_sql_exec.pks
@@plsql/ai_sql_exec.pkb
@@plsql/ai_nl2sql.pks
@@plsql/ai_nl2sql.pkb

prompt === 5.1) Compile check ===
declare
  l_cnt number;
begin
  select count(*)
    into l_cnt
    from user_errors
   where name in ('AI_LOG','AI_SQL_GUARD','AI_SQL_EXEC','AI_NL2SQL')
     and type in ('PACKAGE','PACKAGE BODY');

  if l_cnt > 0 then
    dbms_output.put_line('ERROR: compile errors in NL->SQL packages: ' || l_cnt);
    for r in (
      select name, type, line, position, text
        from user_errors
       where name in ('AI_LOG','AI_SQL_GUARD','AI_SQL_EXEC','AI_NL2SQL')
         and type in ('PACKAGE','PACKAGE BODY')
       order by name, type, sequence
    ) loop
      dbms_output.put_line(r.name || ' ' || r.type || ' ' || r.line || ':' || r.position || ' ' || r.text);
    end loop;
    raise_application_error(-20010, 'Install failed: package compile errors');
  else
    dbms_output.put_line('OK: packages compiled.');
  end if;
end;
/
  
prompt === 6) Smoke ===
@@../scripts/smoke.sql

prompt === install.sql done ===
