--------------------------------------------------------------------------------
-- install_cloud.sql
-- Oracle 19c / APEX Cloud friendly: bez @@, wszystko w jednym pliku.
-- Resetuje obiekty w schemacie (drop + create).
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 0) DROP (best-effort)
--------------------------------------------------------------------------------
declare
  procedure safe(p_sql varchar2, p_ignore number) is
  begin
    execute immediate p_sql;
  exception
    when others then
      if sqlcode != p_ignore then raise; end if;
  end;
begin
  -- packages
  safe('drop package ai_nl2sql', -4043);
  safe('drop package ai_sql_exec', -4043);
  safe('drop package ai_sql_guard', -4043);
  safe('drop package ai_log', -4043);

  -- views (AI first)
  safe('drop view ai_v_sales_order_lines', -942);
  safe('drop view ai_v_sales_order_daily', -942);
  safe('drop view v_sales_orders', -942);
  safe('drop view v_sales_customers', -942);

  -- infra tables
  safe('drop table ai_nl2sql_whitelist purge', -942);
  safe('drop table ai_nl2sql_log purge', -942);

  -- domain tables (children first)
  safe('drop table sales_order_lines purge', -942);
  safe('drop table sales_orders purge', -942);
  safe('drop table sales_products purge', -942);
  safe('drop table sales_customers purge', -942);

  -- lookups
  safe('drop table sales_lu_product_category purge', -942);
  safe('drop table sales_lu_currency purge', -942);
  safe('drop table sales_lu_order_status purge', -942);
  safe('drop table sales_lu_country purge', -942);
  safe('drop table sales_lu_segment purge', -942);
end;
/

--------------------------------------------------------------------------------
-- 1) INFRA: LOG + WHITELIST
--------------------------------------------------------------------------------
create table AI_NL2SQL_LOG (
  log_id        number generated by default as identity primary key,
  request_id    varchar2(32) not null,
  created_at    timestamp default systimestamp not null,
  app_user      varchar2(255),
  question      varchar2(4000),
  view_used     varchar2(128),
  sql_text      clob,
  guard_status  varchar2(30),
  exec_status   varchar2(30),
  row_count     number,
  llm_ms        number,
  exec_ms       number,
  err_code      number,
  err_msg       varchar2(4000)
);

create index AI_NL2SQL_LOG_I1 on AI_NL2SQL_LOG(created_at);
create index AI_NL2SQL_LOG_I2 on AI_NL2SQL_LOG(request_id);

comment on table AI_NL2SQL_LOG is 'NL->SQL: log techniczny requestow (pytanie, sql, guard, czasy).';
comment on column AI_NL2SQL_LOG.log_id is 'PK; techniczny identyfikator logu.';
comment on column AI_NL2SQL_LOG.request_id is 'Id korelacji; przyklad: 32 znaki hex.';
comment on column AI_NL2SQL_LOG.created_at is 'Czas zapisu; timestamp.';
comment on column AI_NL2SQL_LOG.app_user is 'Uzytkownik APEX/DB; identyfikacja aktora.';
comment on column AI_NL2SQL_LOG.question is 'Tekst pytania NL.';
comment on column AI_NL2SQL_LOG.view_used is 'Widok whitelista; np. AI_V_SALES_ORDER_LINES.';
comment on column AI_NL2SQL_LOG.sql_text is 'SQL wygenerowany; tylko SELECT.';
comment on column AI_NL2SQL_LOG.guard_status is 'Wynik guarda; OK/BLOCKED/ERROR.';
comment on column AI_NL2SQL_LOG.exec_status is 'Status wykonania; OK/ERROR.';
comment on column AI_NL2SQL_LOG.row_count is 'Liczba wierszy (opcjonalnie).';
comment on column AI_NL2SQL_LOG.llm_ms is 'Czas LLM call w ms (v0 = 0).';
comment on column AI_NL2SQL_LOG.exec_ms is 'Czas wykonania SQL w ms.';
comment on column AI_NL2SQL_LOG.err_code is 'Kod bledu Oracle.';
comment on column AI_NL2SQL_LOG.err_msg is 'Opis bledu (skrocony).';

create table AI_NL2SQL_WHITELIST (
  view_name   varchar2(128) primary key,
  enabled_yn  char(1) default 'Y' not null,
  purpose     varchar2(1000),
  created_at  timestamp default systimestamp not null
);

comment on table AI_NL2SQL_WHITELIST is 'NL->SQL: whitelista widokow dozwolonych w generowanym SQL.';
comment on column AI_NL2SQL_WHITELIST.view_name is 'PK; nazwa widoku dozwolonego.';
comment on column AI_NL2SQL_WHITELIST.enabled_yn is 'Czy wlaczone; Y/N.';
comment on column AI_NL2SQL_WHITELIST.purpose is 'Opis zastosowania widoku.';
comment on column AI_NL2SQL_WHITELIST.created_at is 'Czas dodania wpisu.';

--------------------------------------------------------------------------------
-- 2) DOMAIN: LOOKUPS
--------------------------------------------------------------------------------
create table SALES_LU_SEGMENT (
  segment_code varchar2(30) primary key,
  segment_desc varchar2(200) not null
);

create table SALES_LU_COUNTRY (
  country_code varchar2(2) primary key,
  country_name varchar2(200) not null
);

create table SALES_LU_ORDER_STATUS (
  status_code varchar2(20) primary key,
  status_desc varchar2(200) not null
);

create table SALES_LU_CURRENCY (
  currency_code varchar2(3) primary key,
  currency_name varchar2(200) not null
);

create table SALES_LU_PRODUCT_CATEGORY (
  category_code varchar2(30) primary key,
  category_desc varchar2(200) not null
);

comment on table SALES_LU_SEGMENT is 'Slownik segmentow klienta. Uzywaj do opisow i filtrow w raportach.';
comment on table SALES_LU_COUNTRY is 'Slownik krajow. Uzywaj do normalizacji i raportowania.';
comment on table SALES_LU_ORDER_STATUS is 'Slownik statusow zamowienia. Uzywaj do mapowania status_code->status_desc.';
comment on table SALES_LU_CURRENCY is 'Slownik walut. Uzywaj do raportow kwot.';
comment on table SALES_LU_PRODUCT_CATEGORY is 'Slownik kategorii produktu. Uzywaj do grupowania sprzedazy.';

comment on column SALES_LU_SEGMENT.segment_code is 'Kod segmentu; klucz; przyklad: B2B.';
comment on column SALES_LU_SEGMENT.segment_desc is 'Opis segmentu; przyklad: Business.';
comment on column SALES_LU_COUNTRY.country_code is 'Kod kraju ISO; klucz; przyklad: PL.';
comment on column SALES_LU_COUNTRY.country_name is 'Nazwa kraju; przyklad: Polska.';
comment on column SALES_LU_ORDER_STATUS.status_code is 'Kod statusu; klucz/status; mapowanie: NEW/PAID/CANCELLED/SHIPPED/CLOSED.';
comment on column SALES_LU_ORDER_STATUS.status_desc is 'Opis statusu; przyklad: New.';
comment on column SALES_LU_CURRENCY.currency_code is 'Kod waluty; klucz; przyklad: PLN.';
comment on column SALES_LU_CURRENCY.currency_name is 'Nazwa waluty; przyklad: Polish zloty.';
comment on column SALES_LU_PRODUCT_CATEGORY.category_code is 'Kod kategorii; klucz; przyklad: APP.';
comment on column SALES_LU_PRODUCT_CATEGORY.category_desc is 'Opis kategorii; przyklad: Apparel.';

--------------------------------------------------------------------------------
-- 3) DOMAIN: ENTITIES
--------------------------------------------------------------------------------
create table SALES_CUSTOMERS (
  customer_id   number generated by default as identity primary key,
  customer_code varchar2(30) not null,
  customer_name varchar2(200) not null,
  segment_code  varchar2(30) not null,
  city          varchar2(200),
  country_code  varchar2(2) not null,
  created_at    date not null,
  is_active     char(1) default 'Y' not null,
  constraint SALES_CUSTOMERS_U1 unique (customer_code),
  constraint SALES_CUSTOMERS_CK1 check (is_active in ('Y','N')),
  constraint SALES_CUSTOMERS_FK1 foreign key (segment_code) references SALES_LU_SEGMENT(segment_code),
  constraint SALES_CUSTOMERS_FK2 foreign key (country_code) references SALES_LU_COUNTRY(country_code)
);

create table SALES_PRODUCTS (
  product_id    number generated by default as identity primary key,
  sku           varchar2(60) not null,
  product_name  varchar2(200) not null,
  category_code varchar2(30) not null,
  is_active     char(1) default 'Y' not null,
  constraint SALES_PRODUCTS_U1 unique (sku),
  constraint SALES_PRODUCTS_CK1 check (is_active in ('Y','N')),
  constraint SALES_PRODUCTS_FK1 foreign key (category_code) references SALES_LU_PRODUCT_CATEGORY(category_code)
);

create table SALES_ORDERS (
  order_id       number generated by default as identity primary key,
  order_no       varchar2(40) not null,
  customer_id    number not null,
  created_at     date not null,
  closed_at      date,
  status_code    varchar2(20) not null,
  currency_code  varchar2(3) not null,
  notes          varchar2(2000),
  constraint SALES_ORDERS_U1 unique (order_no),
  constraint SALES_ORDERS_FK1 foreign key (customer_id) references SALES_CUSTOMERS(customer_id),
  constraint SALES_ORDERS_FK2 foreign key (status_code) references SALES_LU_ORDER_STATUS(status_code),
  constraint SALES_ORDERS_FK3 foreign key (currency_code) references SALES_LU_CURRENCY(currency_code)
);

create table SALES_ORDER_LINES (
  line_id         number generated by default as identity primary key,
  order_id        number not null,
  product_id      number not null,
  qty             number(12,3) not null,
  unit_price_net  number(12,2) not null,
  tax_rate        number(5,4) not null,
  amount_net      number(12,2) not null,
  amount_gross    number(12,2) not null,
  constraint SALES_ORDER_LINES_FK1 foreign key (order_id) references SALES_ORDERS(order_id),
  constraint SALES_ORDER_LINES_FK2 foreign key (product_id) references SALES_PRODUCTS(product_id),
  constraint SALES_ORDER_LINES_CK1 check (qty > 0),
  constraint SALES_ORDER_LINES_CK2 check (unit_price_net >= 0),
  constraint SALES_ORDER_LINES_CK3 check (tax_rate between 0 and 1),
  constraint SALES_ORDER_LINES_CK4 check (amount_net >= 0),
  constraint SALES_ORDER_LINES_CK5 check (amount_gross >= 0)
);

create index SALES_ORDERS_I1 on SALES_ORDERS(customer_id);
create index SALES_ORDERS_I2 on SALES_ORDERS(status_code);
create index SALES_ORDERS_I3 on SALES_ORDERS(currency_code);
create index SALES_ORDER_LINES_I1 on SALES_ORDER_LINES(order_id);
create index SALES_ORDER_LINES_I2 on SALES_ORDER_LINES(product_id);

comment on table SALES_CUSTOMERS is 'Klienci. Zrodlo do raportow i joinow (bez PII).';
comment on table SALES_PRODUCTS is 'Produkty. Zrodlo do raportow sprzedazy; sku stabilny.';
comment on table SALES_ORDERS is 'Zamowienia (naglowki). notes istnieje, ale nie idzie do AI widokow.';
comment on table SALES_ORDER_LINES is 'Pozycje zamowien. Kwoty netto/brutto i ilosci do agregacji.';

comment on column SALES_CUSTOMERS.customer_id is 'PK; klucz techniczny klienta.';
comment on column SALES_CUSTOMERS.customer_code is 'Kod klienta; unikalny; przyklad: CUST-0001.';
comment on column SALES_CUSTOMERS.customer_name is 'Nazwa klienta; przyklad: ACME Sp z o.o.';
comment on column SALES_CUSTOMERS.segment_code is 'Kod segmentu; status/segment; przyklad: B2B.';
comment on column SALES_CUSTOMERS.city is 'Miasto; przyklad: Warszawa.';
comment on column SALES_CUSTOMERS.country_code is 'Kod kraju; przyklad: PL.';
comment on column SALES_CUSTOMERS.created_at is 'Data utworzenia; DATE; przyklad: 2026-02-01.';
comment on column SALES_CUSTOMERS.is_active is 'Czy aktywny; Y/N; przyklad: Y.';

comment on column SALES_PRODUCTS.product_id is 'PK; klucz techniczny produktu.';
comment on column SALES_PRODUCTS.sku is 'Stock Keeping Unit; unikalny kod produktu; przyklad: SKU-TSHIRT-BLK-M.';
comment on column SALES_PRODUCTS.product_name is 'Nazwa produktu; moze sie zmieniac.';
comment on column SALES_PRODUCTS.category_code is 'Kod kategorii; do grupowan; przyklad: APP.';
comment on column SALES_PRODUCTS.is_active is 'Czy aktywny; Y/N.';

comment on column SALES_ORDERS.order_id is 'PK; klucz techniczny zamowienia.';
comment on column SALES_ORDERS.order_no is 'Numer zamowienia; unikalny; przyklad: SO-2026-0001.';
comment on column SALES_ORDERS.customer_id is 'FK do klienta; klucz.';
comment on column SALES_ORDERS.created_at is 'Data utworzenia; DATE.';
comment on column SALES_ORDERS.closed_at is 'Data zamkniecia; NULL gdy otwarte.';
comment on column SALES_ORDERS.status_code is 'Kod statusu; status; mapowanie: NEW/PAID/CANCELLED/SHIPPED/CLOSED.';
comment on column SALES_ORDERS.currency_code is 'Waluta; kod; przyklad: PLN.';
comment on column SALES_ORDERS.notes is 'Notatki wolnotekstowe; nie uzywac w AI widokach.';

comment on column SALES_ORDER_LINES.line_id is 'PK; klucz pozycji.';
comment on column SALES_ORDER_LINES.order_id is 'FK do zamowienia; klucz.';
comment on column SALES_ORDER_LINES.product_id is 'FK do produktu; klucz.';
comment on column SALES_ORDER_LINES.qty is 'Ilosc; jednostka: szt; przyklad: 2.000.';
comment on column SALES_ORDER_LINES.unit_price_net is 'Cena jednostkowa netto; jednostka: waluta; przyklad: 99.99.';
comment on column SALES_ORDER_LINES.tax_rate is 'Stawka VAT; 0..1; przyklad: 0.23.';
comment on column SALES_ORDER_LINES.amount_net is 'Wartosc netto; qty * unit_price_net.';
comment on column SALES_ORDER_LINES.amount_gross is 'Wartosc brutto; amount_net*(1+tax_rate).';

--------------------------------------------------------------------------------
-- 4) SEED DATA (deterministyczne)
--------------------------------------------------------------------------------
insert into SALES_LU_SEGMENT(segment_code, segment_desc) values ('B2B','Business');
insert into SALES_LU_SEGMENT(segment_code, segment_desc) values ('B2C','Consumer');
insert into SALES_LU_SEGMENT(segment_code, segment_desc) values ('VIP','VIP');
insert into SALES_LU_SEGMENT(segment_code, segment_desc) values ('INT','International');

insert into SALES_LU_COUNTRY(country_code, country_name) values ('PL','Polska');
insert into SALES_LU_COUNTRY(country_code, country_name) values ('DE','Niemcy');
insert into SALES_LU_COUNTRY(country_code, country_name) values ('US','USA');

insert into SALES_LU_ORDER_STATUS(status_code, status_desc) values ('NEW','New');
insert into SALES_LU_ORDER_STATUS(status_code, status_desc) values ('PAID','Paid');
insert into SALES_LU_ORDER_STATUS(status_code, status_desc) values ('CANCELLED','Cancelled');
insert into SALES_LU_ORDER_STATUS(status_code, status_desc) values ('SHIPPED','Shipped');
insert into SALES_LU_ORDER_STATUS(status_code, status_desc) values ('CLOSED','Closed');

insert into SALES_LU_CURRENCY(currency_code, currency_name) values ('PLN','Polish zloty');
insert into SALES_LU_CURRENCY(currency_code, currency_name) values ('EUR','Euro');
insert into SALES_LU_CURRENCY(currency_code, currency_name) values ('USD','US Dollar');

insert into SALES_LU_PRODUCT_CATEGORY(category_code, category_desc) values ('APP','Apparel');
insert into SALES_LU_PRODUCT_CATEGORY(category_code, category_desc) values ('HW','Hardware');
insert into SALES_LU_PRODUCT_CATEGORY(category_code, category_desc) values ('SVC','Service');
insert into SALES_LU_PRODUCT_CATEGORY(category_code, category_desc) values ('ACC','Accessories');

insert into SALES_CUSTOMERS(customer_id, customer_code, customer_name, segment_code, city, country_code, created_at, is_active)
values (1,'CUST-0001','ACME Sp z o.o.','B2B','Warszawa','PL',date '2026-02-01','Y');
insert into SALES_CUSTOMERS(customer_id, customer_code, customer_name, segment_code, city, country_code, created_at, is_active)
values (2,'CUST-0002','Beta Retail','B2C','Krakow','PL',date '2026-02-03','Y');
insert into SALES_CUSTOMERS(customer_id, customer_code, customer_name, segment_code, city, country_code, created_at, is_active)
values (3,'CUST-0003','Gamma GmbH','INT','Berlin','DE',date '2026-02-05','Y');
insert into SALES_CUSTOMERS(customer_id, customer_code, customer_name, segment_code, city, country_code, created_at, is_active)
values (4,'CUST-0004','Delta VIP','VIP','Gdansk','PL',date '2026-02-07','Y');
insert into SALES_CUSTOMERS(customer_id, customer_code, customer_name, segment_code, city, country_code, created_at, is_active)
values (5,'CUST-0005','Epsilon Inc.','INT','Austin','US',date '2026-02-09','Y');

insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (1,'SKU-TSHIRT-BLK-M','T-Shirt Black M','APP','Y');
insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (2,'SKU-TSHIRT-WHT-L','T-Shirt White L','APP','Y');
insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (3,'SKU-MOUSE-001','Wireless Mouse','HW','Y');
insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (4,'SKU-KBD-001','Mechanical Keyboard','HW','Y');
insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (5,'SKU-SVC-INSTALL','Installation Service','SVC','Y');
insert into SALES_PRODUCTS(product_id, sku, product_name, category_code, is_active)
values (6,'SKU-CABLE-USB-C','USB-C Cable','ACC','Y');

insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (1,'SO-2026-0001',1,date '2026-02-20',null,'NEW','PLN','internal: call back');
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (2,'SO-2026-0002',2,date '2026-02-20',date '2026-02-21','PAID','PLN',null);
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (3,'SO-2026-0003',3,date '2026-02-21',null,'SHIPPED','EUR',null);
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (4,'SO-2026-0004',4,date '2026-02-22',date '2026-02-22','CANCELLED','PLN','internal: fraud check');
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (5,'SO-2026-0005',5,date '2026-02-23',date '2026-02-25','CLOSED','USD',null);
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (6,'SO-2026-0006',1,date '2026-02-24',date '2026-02-24','PAID','EUR',null);
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (7,'SO-2026-0007',2,date '2026-02-25',null,'NEW','PLN',null);
insert into SALES_ORDERS(order_id, order_no, customer_id, created_at, closed_at, status_code, currency_code, notes)
values (8,'SO-2026-0008',4,date '2026-02-26',null,'SHIPPED','PLN',null);

-- order 1
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (1,1,3,1.000,129.00,0.23,1.000*129.00,round(1.000*129.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (2,1,6,2.000,19.90,0.23,2.000*19.90,round(2.000*19.90*(1+0.23),2));

-- order 2
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (3,2,1,2.000,49.90,0.23,2.000*49.90,round(2.000*49.90*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (4,2,6,1.000,19.90,0.23,1.000*19.90,round(1.000*19.90*(1+0.23),2));

-- order 3
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (5,3,4,1.000,299.00,0.23,1.000*299.00,round(1.000*299.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (6,3,3,1.000,129.00,0.23,1.000*129.00,round(1.000*129.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (7,3,6,3.000,17.90,0.23,3.000*17.90,round(3.000*17.90*(1+0.23),2));

-- order 4
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (8,4,2,1.000,54.90,0.23,1.000*54.90,round(1.000*54.90*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (9,4,5,1.000,199.00,0.23,1.000*199.00,round(1.000*199.00*(1+0.23),2));

-- order 5
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (10,5,4,1.000,329.00,0.23,1.000*329.00,round(1.000*329.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (11,5,6,2.000,22.90,0.23,2.000*22.90,round(2.000*22.90*(1+0.23),2));

-- order 6
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (12,6,3,2.000,119.00,0.23,2.000*119.00,round(2.000*119.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (13,6,5,1.000,149.00,0.23,1.000*149.00,round(1.000*149.00*(1+0.23),2));

-- order 7
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (14,7,1,1.000,49.90,0.23,1.000*49.90,round(1.000*49.90*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (15,7,2,1.000,54.90,0.23,1.000*54.90,round(1.000*54.90*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (16,7,6,1.000,19.90,0.23,1.000*19.90,round(1.000*19.90*(1+0.23),2));

-- order 8
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (17,8,4,1.000,289.00,0.23,1.000*289.00,round(1.000*289.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (18,8,3,1.000,129.00,0.23,1.000*129.00,round(1.000*129.00*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (19,8,6,2.000,19.90,0.23,2.000*19.90,round(2.000*19.90*(1+0.23),2));
insert into SALES_ORDER_LINES(line_id, order_id, product_id, qty, unit_price_net, tax_rate, amount_net, amount_gross)
values (20,8,5,1.000,179.00,0.23,1.000*179.00,round(1.000*179.00*(1+0.23),2));

commit;

--------------------------------------------------------------------------------
-- 5) VIEWS: ENTITY
--------------------------------------------------------------------------------
create or replace view V_SALES_CUSTOMERS as
select
  c.customer_id,
  c.customer_code,
  c.customer_name,
  c.segment_code,
  s.segment_desc,
  c.city,
  c.country_code,
  co.country_name,
  c.created_at,
  c.is_active
from sales_customers c
join sales_lu_segment s on s.segment_code = c.segment_code
join sales_lu_country co on co.country_code = c.country_code;

comment on table V_SALES_CUSTOMERS is 'Widok encji klienta. Uzywaj do joinow i filtrow (bezpieczne pola).';

comment on column V_SALES_CUSTOMERS.customer_id is 'PK klienta; klucz.';
comment on column V_SALES_CUSTOMERS.customer_code is 'Kod klienta; unikalny.';
comment on column V_SALES_CUSTOMERS.customer_name is 'Nazwa klienta.';
comment on column V_SALES_CUSTOMERS.segment_code is 'Kod segmentu.';
comment on column V_SALES_CUSTOMERS.segment_desc is 'Opis segmentu.';
comment on column V_SALES_CUSTOMERS.city is 'Miasto.';
comment on column V_SALES_CUSTOMERS.country_code is 'Kod kraju.';
comment on column V_SALES_CUSTOMERS.country_name is 'Nazwa kraju.';
comment on column V_SALES_CUSTOMERS.created_at is 'Data utworzenia klienta.';
comment on column V_SALES_CUSTOMERS.is_active is 'Czy aktywny; Y/N.';

create or replace view V_SALES_ORDERS as
select
  o.order_id,
  o.order_no,
  o.customer_id,
  c.customer_code,
  c.customer_name,
  o.created_at,
  o.closed_at,
  o.status_code,
  st.status_desc,
  o.currency_code,
  nvl(sum(l.amount_net),0)  as amount_net,
  nvl(sum(l.amount_gross),0) as amount_gross,
  count(l.line_id) as lines_count
from sales_orders o
join sales_customers c on c.customer_id = o.customer_id
join sales_lu_order_status st on st.status_code = o.status_code
left join sales_order_lines l on l.order_id = o.order_id
group by
  o.order_id, o.order_no, o.customer_id, c.customer_code, c.customer_name,
  o.created_at, o.closed_at, o.status_code, st.status_desc, o.currency_code;

comment on table V_SALES_ORDERS is 'Widok encji zamowienia (naglowek + sumy z pozycji). Uzywaj do list i podsumowan.';

comment on column V_SALES_ORDERS.order_id is 'PK zamowienia; klucz.';
comment on column V_SALES_ORDERS.order_no is 'Numer zamowienia; unikalny.';
comment on column V_SALES_ORDERS.customer_id is 'FK klienta; klucz.';
comment on column V_SALES_ORDERS.customer_code is 'Kod klienta.';
comment on column V_SALES_ORDERS.customer_name is 'Nazwa klienta.';
comment on column V_SALES_ORDERS.created_at is 'Data utworzenia.';
comment on column V_SALES_ORDERS.closed_at is 'Data zamkniecia; NULL gdy otwarte.';
comment on column V_SALES_ORDERS.status_code is 'Kod statusu; mapowanie: NEW/PAID/CANCELLED/SHIPPED/CLOSED.';
comment on column V_SALES_ORDERS.status_desc is 'Opis statusu.';
comment on column V_SALES_ORDERS.currency_code is 'Kod waluty.';
comment on column V_SALES_ORDERS.amount_net is 'Suma netto zamowienia; waluta = currency_code.';
comment on column V_SALES_ORDERS.amount_gross is 'Suma brutto zamowienia; waluta = currency_code.';
comment on column V_SALES_ORDERS.lines_count is 'Liczba pozycji zamowienia.';

--------------------------------------------------------------------------------
-- 6) VIEWS: REPORTING (AI whitelist)
--------------------------------------------------------------------------------
create or replace view AI_V_SALES_ORDER_LINES as
select
  o.order_id,
  o.order_no,
  c.customer_id,
  c.customer_code,
  c.customer_name,
  seg.segment_desc as segment_desc,
  o.created_at,
  o.closed_at,
  o.status_code,
  st.status_desc as status_desc,
  o.currency_code,
  p.product_id,
  p.sku,
  p.product_name,
  cat.category_desc as category_desc,
  l.qty,
  l.amount_net,
  l.amount_gross
from sales_order_lines l
join sales_orders o on o.order_id = l.order_id
join sales_customers c on c.customer_id = o.customer_id
join sales_lu_segment seg on seg.segment_code = c.segment_code
join sales_lu_order_status st on st.status_code = o.status_code
join sales_products p on p.product_id = l.product_id
join sales_lu_product_category cat on cat.category_code = p.category_code;

comment on table AI_V_SALES_ORDER_LINES is 'AI whitelist. Pozycje zamowien z klientem i produktem. Uzywaj do analiz per produkt/klient/status.';

comment on column AI_V_SALES_ORDER_LINES.order_id is 'PK zamowienia; klucz.';
comment on column AI_V_SALES_ORDER_LINES.order_no is 'Numer zamowienia.';
comment on column AI_V_SALES_ORDER_LINES.customer_id is 'PK klienta; klucz.';
comment on column AI_V_SALES_ORDER_LINES.customer_code is 'Kod klienta.';
comment on column AI_V_SALES_ORDER_LINES.customer_name is 'Nazwa klienta.';
comment on column AI_V_SALES_ORDER_LINES.segment_desc is 'Segment klienta; przyklad: Business.';
comment on column AI_V_SALES_ORDER_LINES.created_at is 'Data utworzenia zamowienia.';
comment on column AI_V_SALES_ORDER_LINES.closed_at is 'Data zamkniecia; NULL gdy otwarte.';
comment on column AI_V_SALES_ORDER_LINES.status_code is 'Kod statusu; mapowanie: NEW/PAID/CANCELLED/SHIPPED/CLOSED.';
comment on column AI_V_SALES_ORDER_LINES.status_desc is 'Opis statusu.';
comment on column AI_V_SALES_ORDER_LINES.currency_code is 'Waluta; kod.';
comment on column AI_V_SALES_ORDER_LINES.product_id is 'PK produktu; klucz.';
comment on column AI_V_SALES_ORDER_LINES.sku is 'Kod produktu (SKU).';
comment on column AI_V_SALES_ORDER_LINES.product_name is 'Nazwa produktu.';
comment on column AI_V_SALES_ORDER_LINES.category_desc is 'Kategoria produktu.';
comment on column AI_V_SALES_ORDER_LINES.qty is 'Ilosc; jednostka: szt.';
comment on column AI_V_SALES_ORDER_LINES.amount_net is 'Wartosc netto pozycji; waluta = currency_code.';
comment on column AI_V_SALES_ORDER_LINES.amount_gross is 'Wartosc brutto pozycji; waluta = currency_code.';

create or replace view AI_V_SALES_ORDER_DAILY as
select
  trunc(o.created_at) as sales_date,
  o.status_code,
  st.status_desc as status_desc,
  o.currency_code,
  count(distinct o.order_id) as orders_count,
  sum(l.qty) as qty_sum,
  sum(l.amount_net) as amount_net_sum,
  sum(l.amount_gross) as amount_gross_sum
from sales_orders o
join sales_lu_order_status st on st.status_code = o.status_code
join sales_order_lines l on l.order_id = o.order_id
group by trunc(o.created_at), o.status_code, st.status_desc, o.currency_code;

comment on table AI_V_SALES_ORDER_DAILY is 'AI whitelist. Agregacja dzienna per status i waluta. Uzywaj do trendow i wykresow.';

comment on column AI_V_SALES_ORDER_DAILY.sales_date is 'Dzien sprzedazy; TRUNC(created_at).';
comment on column AI_V_SALES_ORDER_DAILY.status_code is 'Kod statusu; mapowanie: NEW/PAID/CANCELLED/SHIPPED/CLOSED.';
comment on column AI_V_SALES_ORDER_DAILY.status_desc is 'Opis statusu.';
comment on column AI_V_SALES_ORDER_DAILY.currency_code is 'Waluta; kod.';
comment on column AI_V_SALES_ORDER_DAILY.orders_count is 'Liczba zamowien (distinct order_id).';
comment on column AI_V_SALES_ORDER_DAILY.qty_sum is 'Suma ilosci (pozycje).';
comment on column AI_V_SALES_ORDER_DAILY.amount_net_sum is 'Suma netto; waluta = currency_code.';
comment on column AI_V_SALES_ORDER_DAILY.amount_gross_sum is 'Suma brutto; waluta = currency_code.';

--------------------------------------------------------------------------------
-- 7) WHITELIST SEED
--------------------------------------------------------------------------------
merge into AI_NL2SQL_WHITELIST t
using (
  select 'AI_V_SALES_ORDER_LINES' view_name, 'Y' enabled_yn,
         'Pozycje zamowien z klientem i produktem.' purpose from dual
  union all
  select 'AI_V_SALES_ORDER_DAILY', 'Y',
         'Agregacja dzienna per status i waluta.' from dual
) s
on (t.view_name = s.view_name)
when matched then update set t.enabled_yn = s.enabled_yn, t.purpose = s.purpose
when not matched then insert (view_name, enabled_yn, purpose) values (s.view_name, s.enabled_yn, s.purpose);

commit;

--------------------------------------------------------------------------------
-- 8) PACKAGES v0 (stub NL->SQL)
--------------------------------------------------------------------------------
create or replace package ai_log as
  function new_request_id return varchar2;

  procedure write(
    p_request_id   in varchar2,
    p_app_user     in varchar2,
    p_question     in varchar2,
    p_view_used    in varchar2,
    p_sql_text     in clob,
    p_guard_status in varchar2,
    p_exec_status  in varchar2,
    p_row_count    in number,
    p_llm_ms       in number,
    p_exec_ms      in number,
    p_err_code     in number,
    p_err_msg      in varchar2
  );
end ai_log;
/
create or replace package body ai_log as
  function new_request_id return varchar2 is
  begin
    return lower(rawtohex(sys_guid()));
  end;

  procedure write(
    p_request_id   in varchar2,
    p_app_user     in varchar2,
    p_question     in varchar2,
    p_view_used    in varchar2,
    p_sql_text     in clob,
    p_guard_status in varchar2,
    p_exec_status  in varchar2,
    p_row_count    in number,
    p_llm_ms       in number,
    p_exec_ms      in number,
    p_err_code     in number,
    p_err_msg      in varchar2
  ) is
  begin
    insert into ai_nl2sql_log(
      request_id, app_user, question, view_used, sql_text,
      guard_status, exec_status, row_count, llm_ms, exec_ms, err_code, err_msg
    ) values (
      p_request_id, p_app_user, substr(p_question,1,4000), p_view_used, p_sql_text,
      substr(p_guard_status,1,30), substr(p_exec_status,1,30), p_row_count, p_llm_ms, p_exec_ms, p_err_code, substr(p_err_msg,1,4000)
    );
  end;
end ai_log;
/

create or replace package ai_sql_guard as
  procedure validate(
    p_sql_in    in  clob,
    p_limit     in  number,
    o_sql_out   out clob,
    o_status    out varchar2,
    o_reason    out varchar2,
    o_view_used out varchar2
  );
end ai_sql_guard;
/
create or replace package body ai_sql_guard as
  function norm_limit(p_limit number) return number is
  begin
    return least(greatest(nvl(p_limit, 50), 1), 500);
  end;

  procedure validate(
    p_sql_in    in  clob,
    p_limit     in  number,
    o_sql_out   out clob,
    o_status    out varchar2,
    o_reason    out varchar2,
    o_view_used out varchar2
  ) is
    l_sql      clob;
    l_u        clob;
    l_limit    number := norm_limit(p_limit);
    l_cur      integer;
    l_view     varchar2(128);
    l_occ      number := 1;
    l_found    number := 0;
    l_enabled  number;
  begin
    o_sql_out := null;
    o_status := 'ERROR';
    o_reason := null;
    o_view_used := null;

    l_sql := trim(p_sql_in);

    if l_sql is null then
      o_status := 'BLOCKED';
      o_reason := 'EMPTY_SQL';
      return;
    end if;

    if substr(l_sql, -1) = ';' then
      l_sql := substr(l_sql, 1, length(l_sql)-1);
    end if;

    l_u := upper(l_sql);

    if not regexp_like(l_u, '^\s*SELECT\b') then
      o_status := 'BLOCKED';
      o_reason := 'ONLY_SELECT_ALLOWED';
      return;
    end if;

    if regexp_like(l_u, '\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|COMMIT|ROLLBACK|BEGIN|DECLARE)\b') then
      o_status := 'BLOCKED';
      o_reason := 'FORBIDDEN_KEYWORD';
      return;
    end if;

    if regexp_like(l_u, '\b(DBMS_|UTL_|HTTPURITYPE|ORDS|APEX_)\b') then
      o_status := 'BLOCKED';
      o_reason := 'FORBIDDEN_PACKAGE';
      return;
    end if;

    if regexp_like(l_u, '\b(DBA_|ALL_USERS|USER_USERS|V\$_|GV\$_)\b') then
      o_status := 'BLOCKED';
      o_reason := 'FORBIDDEN_DICTIONARY';
      return;
    end if;

    if regexp_like(l_u, '\bSALES_[A-Z0-9_]+\b') or regexp_like(l_u, '\bV_SALES_[A-Z0-9_]+\b') then
      o_status := 'BLOCKED';
      o_reason := 'ONLY_AI_VIEWS_ALLOWED';
      return;
    end if;

    loop
      l_view := regexp_substr(l_u, 'AI_V_SALES_[A-Z0-9_]+', 1, l_occ);
      exit when l_view is null;

      l_occ := l_occ + 1;
      l_found := 1;
      o_view_used := l_view;

      select count(*)
        into l_enabled
        from ai_nl2sql_whitelist
       where view_name = l_view
         and enabled_yn = 'Y';

      if l_enabled = 0 then
        o_status := 'BLOCKED';
        o_reason := 'VIEW_NOT_WHITELISTED: ' || l_view;
        return;
      end if;
    end loop;

    if l_found = 0 then
      o_status := 'BLOCKED';
      o_reason := 'NO_AI_VIEW_USED';
      return;
    end if;

    if not regexp_like(l_u, '\bFETCH\s+FIRST\s+\d+\s+ROWS\s+ONLY\b') then
      o_sql_out := l_sql || ' fetch first ' || to_char(l_limit) || ' rows only';
    else
      o_sql_out := l_sql;
    end if;

    l_cur := dbms_sql.open_cursor;
    begin
      dbms_sql.parse(l_cur, o_sql_out, dbms_sql.native);
    exception
      when others then
        o_status := 'BLOCKED';
        o_reason := 'PARSE_ERROR: ' || substr(sqlerrm, 1, 900);
        dbms_sql.close_cursor(l_cur);
        return;
    end;
    dbms_sql.close_cursor(l_cur);

    o_status := 'OK';
    o_reason := 'OK';
  end validate;
end ai_sql_guard;
/

create or replace package ai_sql_exec as
  function run(
    p_sql   in clob,
    p_limit in number default 50
  ) return sys_refcursor;
end ai_sql_exec;
/
create or replace package body ai_sql_exec as
  function norm_limit(p_limit number) return number is
  begin
    return least(greatest(nvl(p_limit, 50), 1), 500);
  end;

  function strip_semicolon(p_sql clob) return clob is
    l_sql clob := trim(p_sql);
  begin
    if l_sql is not null and substr(l_sql, -1) = ';' then
      l_sql := substr(l_sql, 1, length(l_sql)-1);
    end if;
    return l_sql;
  end;

  function run(
    p_sql   in clob,
    p_limit in number default 50
  ) return sys_refcursor is
    l_rc sys_refcursor;
    l_sql clob;
    l_u   clob;
    l_limit number := norm_limit(p_limit);
  begin
    l_sql := strip_semicolon(p_sql);
    l_u := upper(l_sql);

    if regexp_like(l_u, '\bFETCH\s+FIRST\s+\d+\s+ROWS\s+ONLY\b') then
      open l_rc for l_sql;
    else
      open l_rc for (l_sql || ' fetch first ' || to_char(l_limit) || ' rows only');
    end if;

    return l_rc;
  end run;
end ai_sql_exec;
/

create or replace package ai_nl2sql as
  function generate(
    p_question in varchar2,
    p_limit    in number default 50
  ) return clob;

  procedure run(
    p_question   in  varchar2,
    p_limit      in  number default 50,
    p_app_user   in  varchar2 default null,
    o_request_id out varchar2,
    o_sql        out clob,
    o_rc         out sys_refcursor
  );
end ai_nl2sql;
/
create or replace package body ai_nl2sql as
  function norm_limit(p_limit number) return number is
  begin
    return least(greatest(nvl(p_limit, 50), 1), 500);
  end;

  function pick_status_code(p_q varchar2) return varchar2 is
    l_q varchar2(4000) := lower(nvl(p_q,''));
  begin
    if instr(l_q, 'new') > 0 or instr(l_q, 'nowe') > 0 then return 'NEW'; end if;
    if instr(l_q, 'paid') > 0 or instr(l_q, 'oplac') > 0 then return 'PAID'; end if;
    if instr(l_q, 'cancel') > 0 or instr(l_q, 'anul') > 0 then return 'CANCELLED'; end if;
    if instr(l_q, 'ship') > 0 or instr(l_q, 'wysyl') > 0 then return 'SHIPPED'; end if;
    if instr(l_q, 'closed') > 0 or instr(l_q, 'zamkn') > 0 then return 'CLOSED'; end if;
    return null;
  end;

  function pick_currency(p_q varchar2) return varchar2 is
    l_q varchar2(4000) := lower(nvl(p_q,''));
  begin
    if instr(l_q, 'pln') > 0 then return 'PLN'; end if;
    if instr(l_q, 'eur') > 0 then return 'EUR'; end if;
    if instr(l_q, 'usd') > 0 then return 'USD'; end if;
    return null;
  end;

  function pick_date_literal(p_q varchar2) return varchar2 is
  begin
    return regexp_substr(p_q, '(20[0-9]{2}-[0-9]{2}-[0-9]{2})', 1, 1);
  end;

  function generate(
    p_question in varchar2,
    p_limit    in number default 50
  ) return clob is
    l_q       varchar2(4000) := lower(nvl(p_question,''));
    l_limit   number := norm_limit(p_limit);
    l_view    varchar2(128);
    l_sql     clob;
    l_status  varchar2(20);
    l_curr    varchar2(3);
    l_date    varchar2(10);
    l_where   varchar2(2000) := ' where 1=1 ';
    l_order   varchar2(2000) := '';
    l_json    clob;
  begin
    if instr(l_q, 'pozyc') > 0 or instr(l_q, 'produkt') > 0 or instr(l_q, 'sku') > 0 then
      l_view := 'AI_V_SALES_ORDER_LINES';
    else
      l_view := 'AI_V_SALES_ORDER_DAILY';
    end if;

    l_status := pick_status_code(l_q);
    l_curr   := pick_currency(l_q);
    l_date   := pick_date_literal(l_q);

    if l_view = 'AI_V_SALES_ORDER_LINES' then
      if l_status is not null then l_where := l_where || ' and status_code = ''' || l_status || ''' '; end if;
      if l_curr is not null then l_where := l_where || ' and currency_code = ''' || l_curr || ''' '; end if;
      if l_date is not null then l_where := l_where || ' and trunc(created_at) = date ''' || l_date || ''' '; end if;

      if instr(l_q, 'naj') > 0 or instr(l_q, 'top') > 0 then
        l_order := ' order by amount_gross desc ';
      else
        l_order := ' order by created_at desc, order_id desc ';
      end if;

      l_sql :=
        'select order_id, order_no, customer_id, customer_code, customer_name, segment_desc, ' ||
        'created_at, closed_at, status_code, status_desc, currency_code, ' ||
        'product_id, sku, product_name, category_desc, qty, amount_net, amount_gross ' ||
        'from AI_V_SALES_ORDER_LINES' || l_where || l_order ||
        ' fetch first ' || to_char(l_limit) || ' rows only';
    else
      if l_status is not null then l_where := l_where || ' and status_code = ''' || l_status || ''' '; end if;
      if l_curr is not null then l_where := l_where || ' and currency_code = ''' || l_curr || ''' '; end if;
      if l_date is not null then l_where := l_where || ' and sales_date = date ''' || l_date || ''' '; end if;

      if instr(l_q, 'naj') > 0 or instr(l_q, 'top') > 0 then
        l_order := ' order by amount_gross_sum desc ';
      else
        l_order := ' order by sales_date desc, status_code, currency_code ';
      end if;

      l_sql :=
        'select sales_date, status_code, status_desc, currency_code, ' ||
        'orders_count, qty_sum, amount_net_sum, amount_gross_sum ' ||
        'from AI_V_SALES_ORDER_DAILY' || l_where || l_order ||
        ' fetch first ' || to_char(l_limit) || ' rows only';
    end if;

    select json_object(
             'view_used' value l_view,
             'limit'     value l_limit,
             'sql'       value l_sql,
             'llm_ms'    value 0
             returning clob
           )
      into l_json
      from dual;

    return l_json;
  end generate;

  procedure run(
    p_question   in  varchar2,
    p_limit      in  number default 50,
    p_app_user   in  varchar2 default null,
    o_request_id out varchar2,
    o_sql        out clob,
    o_rc         out sys_refcursor
  ) is
    l_req      varchar2(32);
    l_gen      clob;
    l_view     varchar2(128);
    l_sql_in   clob;
    l_sql_out  clob;
    l_gstat    varchar2(30);
    l_greason  varchar2(1000);
    l_exec_ms  number;
    t0         number;
    t1         number;
  begin
    l_req := ai_log.new_request_id;
    o_request_id := l_req;

    l_gen := generate(p_question, p_limit);
    l_view := json_value(l_gen, '$.view_used');
    l_sql_in := json_value(l_gen, '$.sql' returning clob);

    ai_sql_guard.validate(
      p_sql_in    => l_sql_in,
      p_limit     => p_limit,
      o_sql_out   => l_sql_out,
      o_status    => l_gstat,
      o_reason    => l_greason,
      o_view_used => l_view
    );

    if l_gstat <> 'OK' then
      ai_log.write(l_req, p_app_user, p_question, l_view, l_sql_in, l_gstat, 'BLOCKED', null, 0, null, null, null);
      commit;
      raise_application_error(-20002, 'NL->SQL blocked: ' || l_greason);
    end if;

    t0 := dbms_utility.get_time;
    begin
      o_rc := ai_sql_exec.run(l_sql_out, p_limit);
      t1 := dbms_utility.get_time;
      l_exec_ms := (t1 - t0) * 10;

      o_sql := l_sql_out;

      ai_log.write(l_req, p_app_user, p_question, l_view, l_sql_out, 'OK', 'OK', null, 0, l_exec_ms, null, null);
      commit;
    exception
      when others then
        t1 := dbms_utility.get_time;
        l_exec_ms := (t1 - t0) * 10;
        ai_log.write(l_req, p_app_user, p_question, l_view, l_sql_out, 'OK', 'ERROR', null, 0, l_exec_ms, sqlcode, sqlerrm);
        commit;
        raise;
    end;
  end run;
end ai_nl2sql;
/

--------------------------------------------------------------------------------
-- 9) COMPILE CHECK (fail-fast)
--------------------------------------------------------------------------------
declare
  l_cnt number;
begin
  select count(*)
    into l_cnt
    from user_errors
   where name in ('AI_LOG','AI_SQL_GUARD','AI_SQL_EXEC','AI_NL2SQL')
     and type in ('PACKAGE','PACKAGE BODY');

  if l_cnt > 0 then
    raise_application_error(-20010, 'Install failed: package compile errors: ' || l_cnt);
  end if;
end;
/

--------------------------------------------------------------------------------
-- 10) SMOKE
--------------------------------------------------------------------------------
select
  order_no, customer_name, status_desc, created_at, qty, amount_gross, currency_code
from ai_v_sales_order_lines
order by created_at desc, order_id desc, product_id
fetch first 5 rows only;

select
  sales_date, status_desc, currency_code, orders_count, qty_sum, amount_gross_sum
from ai_v_sales_order_daily
order by sales_date desc, status_code, currency_code
fetch first 10 rows only;

select
  order_no, customer_name, status_desc, created_at, closed_at, amount_gross, lines_count, currency_code
from v_sales_orders
order by created_at desc, order_id desc
fetch first 5 rows only;

declare
  l_missing_cnt number;
begin
  select count(*)
    into l_missing_cnt
    from user_tab_columns c
    left join user_col_comments cc
      on cc.table_name = c.table_name
     and cc.column_name = c.column_name
   where c.table_name like 'AI\_V\_SALES\_%' escape '\'
     and (cc.comments is null or trim(cc.comments) is null);

  if l_missing_cnt > 0 then
    raise_application_error(-20001, 'Smoke failed: missing column comments in AI_V_SALES_*: ' || l_missing_cnt);
  end if;
end;
/
